
import React, { useState, useEffect } from 'react';
import { api } from '../services/api';
import { Transaction, User } from '../types';
import anime from 'animejs';

const Payments: React.FC = () => {
  const [transactions, setTransactions] = useState<Transaction[]>([]);
  const [searchTerm, setSearchTerm] = useState('');
  const [typeFilter, setTypeFilter] = useState('All');
  const [currentUser, setCurrentUser] = useState<User | null>(null);
  const [selectedTx, setSelectedTx] = useState<Transaction | null>(null);

  useEffect(() => {
    const user = api.getCurrentUser();
    setCurrentUser(user);

    const fetchTransactions = async () => {
      const data = await api.getTransactions();
      if (user && user.role !== 'Admin') {
        setTransactions(data.filter(t => t.userId === user.id || t.entityName === user.name));
      } else {
        setTransactions(data);
      }
    };
    fetchTransactions();
  }, []);

  useEffect(() => {
    if (transactions.length > 0) {
      (anime as any)({
        targets: '.ledger-row',
        opacity: [0, 1],
        translateX: [-15, 0],
        delay: anime.stagger(30),
        easing: 'easeOutSine',
        duration: 500
      });
    }
  }, [transactions, searchTerm, typeFilter]);

  const filteredTransactions = transactions.filter(t => {
    const matchesSearch = t.entityName.toLowerCase().includes(searchTerm.toLowerCase()) || 
                          t.productName.toLowerCase().includes(searchTerm.toLowerCase());
    const matchesType = typeFilter === 'All' || t.type === typeFilter;
    return matchesSearch && matchesType;
  });

  const pendingIncoming = transactions.filter(t => t.type === 'Sale' && t.status === 'Pending').reduce((acc, t) => acc + t.totalAmount, 0);
  const pendingOutgoing = transactions.filter(t => t.type === 'Purchase' && t.status === 'Pending').reduce((acc, t) => acc + t.totalAmount, 0);

  const handlePrint = () => { window.print(); };

  const handleDownload = (tx: Transaction) => {
    const content = `INVOICE - TEXFLOW\n-----------------\nRef: #${tx.id.toUpperCase()}\nType: ${tx.type}\nClient: ${tx.entityName}\nTotal: INR ${tx.totalAmount}\nGenerated by TexFlow`;
    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `Invoice_${tx.id.slice(-6)}.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="space-y-12 pb-24">
      {/* Finance Bento Cards */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-10">
        <div className="bg-[#00a86b] p-12 rounded-[3.5rem] shadow-2xl text-white relative overflow-hidden group">
          <div className="relative z-10">
            <p className="text-emerald-100 text-[10px] font-black uppercase tracking-[0.4em] mb-4 opacity-80">
              {currentUser?.role === 'Admin' ? 'Uncollected Revenue' : 'Portfolio Settlement Value'}
            </p>
            <h4 className="text-7xl font-black tracking-tighter">
              ₹{(currentUser?.role === 'Admin' ? pendingIncoming : transactions.reduce((a,c) => a+c.totalAmount, 0)).toLocaleString()}
            </h4>
            {currentUser?.role === 'Admin' && (
              <button className="mt-8 bg-white/10 hover:bg-white/20 backdrop-blur-md px-8 py-3 rounded-2xl text-[10px] font-black uppercase tracking-widest transition-all border border-white/20">
                Collect Revenue
              </button>
            )}
          </div>
          <div className="absolute -bottom-20 -right-20 opacity-10 group-hover:scale-125 transition-transform duration-1000">
             <svg className="h-80 w-80" fill="currentColor" viewBox="0 0 24 24"><path d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm1.41 16.09V20h-2.82v-1.91c-1.57-.33-3.13-1.1-4.06-2.26l1.45-1.45c.7.83 1.83 1.38 2.61 1.63 1.57.51 3.29-.02 3.29-1.93 0-1.12-.52-1.74-1.45-2.22l-1.55-.79C8.94 10.11 7.4 9.17 7.4 7.21c0-1.79 1.31-3.23 3.19-3.7V2h2.82v1.51c1.39.29 2.58.91 3.42 1.81l-1.45 1.45c-.6-.6-1.44-1.01-1.97-1.18-1.44-.46-2.95.12-2.95 1.76 0 1.05.61 1.61 1.35 1.99l1.55.79c1.94.99 3.12 1.95 3.12 4.1.01 2.05-1.39 3.51-3.51 4.07z"/></svg>
          </div>
        </div>

        <div className="bg-[#ef3340] p-12 rounded-[3.5rem] shadow-2xl text-white relative overflow-hidden group">
          <div className="relative z-10">
            <p className="text-rose-100 text-[10px] font-black uppercase tracking-[0.4em] mb-4 opacity-80">
              {currentUser?.role === 'Admin' ? 'Outstanding Dues' : 'Voucher Inventory'}
            </p>
            <h4 className="text-7xl font-black tracking-tighter">
              {currentUser?.role === 'Admin' ? `₹${pendingOutgoing.toLocaleString()}` : transactions.length}
            </h4>
            {currentUser?.role === 'Admin' && (
              <button className="mt-8 bg-white/10 hover:bg-white/20 backdrop-blur-md px-8 py-3 rounded-2xl text-[10px] font-black uppercase tracking-widest transition-all border border-white/20">
                Settle Payables
              </button>
            )}
          </div>
          <div className="absolute -bottom-20 -right-20 opacity-10 group-hover:scale-125 transition-transform duration-1000">
             <svg className="h-80 w-80" fill="currentColor" viewBox="0 0 24 24"><path d="M3 13h18c0.55 0 1-0.45 1-1s-0.45-1-1-1H3c-0.55 0-1 0.45-1 1s0.45 1 1 1zm0-4h18c0.55 0 1-0.45 1-1s-0.45-1-1-1H3c-0.55 0-1 0.45-1 1s0.45 1 1 1zm0 8h18c0.55 0 1-0.45 1-1s-0.45-1-1-1H3c-0.55 0-1 0.45-1 1s0.45 1 1 1z"/></svg>
          </div>
        </div>
      </div>

      {/* Ledger Section */}
      <div className="glass-card rounded-[4.5rem] border border-white/60 overflow-hidden shadow-3xl bg-white">
        <div className="p-16 border-b border-slate-50">
          <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-10">
            <div>
              <h4 className="text-5xl font-black text-slate-900 tracking-tighter">Settlement Ledger</h4>
              <p className="text-slate-400 text-[11px] font-black uppercase tracking-[0.5em] mt-2">Verified Financial Records</p>
            </div>
            <div className="flex flex-wrap gap-5 w-full md:w-auto">
              <input 
                type="text" 
                placeholder="Search ledger..." 
                className="px-8 py-5 glass-input rounded-3xl font-extrabold text-xs outline-none w-full md:w-80"
                value={searchTerm}
                onChange={(e) => setSearchTerm(e.target.value)}
              />
            </div>
          </div>
        </div>
        
        <div className="overflow-x-auto">
          <table className="w-full text-left">
            <thead className="bg-slate-50/30">
              <tr>
                <th className="px-12 py-12 text-[10px] font-black text-slate-400 uppercase tracking-[0.4em]">Date</th>
                {currentUser?.role === 'Admin' && (
                  <th className="px-12 py-12 text-[10px] font-black text-slate-400 uppercase tracking-[0.4em]">Account Holder</th>
                )}
                <th className="px-12 py-12 text-[10px] font-black text-slate-400 uppercase tracking-[0.4em]">Description</th>
                <th className="px-12 py-12 text-[10px] font-black text-slate-400 uppercase tracking-[0.4em] text-right">Net Amount</th>
                <th className="px-12 py-12 text-[10px] font-black text-slate-400 uppercase tracking-[0.4em] text-center">Invoice</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-50">
              {filteredTransactions.map(t => (
                <tr key={t.id} className="ledger-row hover:bg-slate-50/50 transition-colors opacity-0 group">
                  <td className="px-12 py-12">
                    <span className="font-extrabold text-slate-900 text-sm">{new Date(t.date).toLocaleDateString()}</span>
                  </td>
                  {currentUser?.role === 'Admin' && (
                    <td className="px-12 py-12">
                      <span className="font-black text-slate-800 text-sm tracking-tight">{t.entityName}</span>
                    </td>
                  )}
                  <td className="px-12 py-12">
                    <p className="font-black text-slate-900 text-2xl leading-none tracking-tight mb-2">{t.productName}</p>
                    <p className="text-[11px] text-indigo-500 font-black uppercase tracking-[0.2em]">{t.status}</p>
                  </td>
                  <td className="px-12 py-12 font-black text-3xl text-slate-900 tracking-tighter text-right">₹{t.totalAmount.toLocaleString()}</td>
                  <td className="px-12 py-12 text-center">
                    <button 
                      onClick={() => setSelectedTx(t)}
                      className="p-4 rounded-2xl bg-slate-50 group-hover:bg-indigo-600 group-hover:text-white transition-all text-slate-400"
                    >
                      <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" strokeWidth="2"/></svg>
                    </button>
                  </td>
                </tr>
              ))}
              {filteredTransactions.length === 0 && (
                <tr><td colSpan={currentUser?.role === 'Admin' ? 5 : 4} className="py-40 text-center text-slate-300 font-black uppercase text-xs tracking-[0.5em] opacity-40">Zero transaction matches.</td></tr>
              )}
            </tbody>
          </table>
        </div>
      </div>

      {/* Modal for Invoice */}
      {selectedTx && (
        <div className="fixed inset-0 z-[120] flex items-center justify-center p-6 bg-slate-900/40 backdrop-blur-2xl no-print">
          <div id="printable-invoice" className="bg-white glass-card rounded-[4rem] w-full max-w-2xl p-16 shadow-3xl animate-in slide-in-from-bottom duration-300 relative overflow-hidden flex flex-col max-h-[90vh]">
             <div className="flex justify-between items-start mb-12">
                <div>
                   <h3 className="text-4xl font-black text-slate-900 tracking-tighter leading-none mb-2">My Voucher</h3>
                   <p className="text-indigo-600 font-black text-[10px] uppercase tracking-[0.3em]">REF: #{selectedTx.id.toUpperCase()}</p>
                </div>
                <button onClick={() => setSelectedTx(null)} className="p-2 text-slate-300 hover:text-slate-900 transition-colors no-print">
                   <svg className="w-10 h-10" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path d="M6 18L18 6M6 6l12 12" strokeWidth="2.5"/></svg>
                </button>
             </div>
             <div className="flex-1 overflow-y-auto space-y-12 pr-4 custom-scrollbar">
                <div className="grid grid-cols-2 gap-8 border-b border-slate-50 pb-12">
                   <div>
                      <p className="text-[10px] font-black text-slate-400 uppercase tracking-[0.3em] mb-4">Account Holder</p>
                      <p className="text-2xl font-black text-slate-900 tracking-tight">{selectedTx.entityName}</p>
                      <p className="text-sm font-bold text-slate-500 mt-2">{selectedTx.customerPhone || currentUser?.phone}</p>
                   </div>
                   {selectedTx.shippingAddress && (
                      <div>
                         <p className="text-[10px] font-black text-indigo-500 uppercase tracking-[0.3em] mb-4">Destination</p>
                         <p className="text-sm font-bold text-slate-700 leading-relaxed italic whitespace-pre-line">{selectedTx.shippingAddress}</p>
                      </div>
                   )}
                </div>
                <div className="space-y-8">
                   <div className="flex justify-between items-start">
                      <div className="space-y-2">
                         <p className="text-3xl font-black text-slate-900 tracking-tight">{selectedTx.productName}</p>
                         <p className="text-xs font-black text-slate-400 uppercase tracking-[0.2em]">₹{selectedTx.unitPrice.toLocaleString()} × {selectedTx.quantity} units</p>
                      </div>
                      <p className="text-3xl font-black text-slate-900 tracking-tighter">₹{(selectedTx.unitPrice * selectedTx.quantity).toLocaleString()}</p>
                   </div>
                </div>
                <div className="pt-12 border-t border-slate-100 space-y-6">
                   <div className="flex justify-between items-center pt-10">
                      <span className="text-xs font-black text-slate-400 uppercase tracking-[0.5em]">Total Value</span>
                      <span className="text-7xl font-black text-indigo-600 tracking-tighter">₹{selectedTx.totalAmount.toLocaleString()}</span>
                   </div>
                </div>
             </div>
             <div className="mt-16 pt-10 border-t border-slate-50 grid grid-cols-2 gap-6 no-print">
                <button onClick={handlePrint} className="py-6 bg-slate-900 text-white rounded-[2rem] font-black text-xs uppercase tracking-widest flex items-center justify-center gap-3 hover:bg-black transition-all">Print Statement</button>
                <button onClick={() => handleDownload(selectedTx)} className="py-6 border-2 border-slate-100 text-slate-900 rounded-[2rem] font-black text-xs uppercase tracking-widest flex items-center justify-center gap-3 hover:bg-slate-50 transition-all">Save PDF</button>
             </div>
          </div>
        </div>
      )}
      <style>{`
        @media print { .no-print { display: none !important; } #printable-invoice { width: 100% !important; max-width: none !important; box-shadow: none !important; border: none !important; } }
        .custom-scrollbar::-webkit-scrollbar { width: 4px; }
        .custom-scrollbar::-webkit-scrollbar-thumb { background: rgba(0,0,0,0.05); border-radius: 10px; }
      `}</style>
    </div>
  );
};

export default Payments;
